There was an issue of two methods create_user in the authentication_m…
samuelhilpert/eduvmstore pull request #66
Opened 2024-11-29 14:59 UTC by samuelhilpert

…iddleware.py, both two methods have been combined to one

### Description
Short description about what your commits do.
Focus on what and why instead of where and how.

2024-11-29 17:02 UTC, JaredHeinrich requested changes

2024-11-29 17:08 UTC, val-cze commented on eduvmstorebackend/eduvmstore/middleware/authentication_middleware.py
> +            user_dict = {
weiß nicht, ob user so das richtige wort ist, weil es ja nur teil eines users ist, der dann den user erzeugt

2024-11-30 05:30 UTC, rickertmar requested changes
Ich hab noch ein 1-2 Kommentare geschrieben.

Außerdem bitte gucken, dass vor einem PR weiterhin alle Tests erfolgreich durchlaufen und wenn möglich auch auf das Ruff Linting achten.

2024-11-30 05:30 UTC, rickertmar commented on eduvmstorebackend/eduvmstore/middleware/authentication_middleware.py
> +            create_user(user_dict)
funktioniert das so richtig?
Oder muss es `user = create_user(user_dict)` sein, damit dieser richtig returnt wird?

2024-11-30 05:30 UTC, rickertmar commented on eduvmstorebackend/eduvmstore/middleware/authentication_middleware.py
Ich kann aus irgendeinem Grund keinen Kommentar bei den letzten Zeilen der Datei schreiben, deshalb hier:

In der Methode get_required_access_level muss das route_mapping auch an die Änderung im access_level.py file angepasst werden.

2024-12-01 19:27 UTC, val-cze commented on eduvmstorebackend/eduvmstore/middleware/authentication_middleware.py
> +            create_user(user_dict)
ja, sehr gut, good find. Fixed now.

2024-12-01 19:28 UTC, val-cze commented on eduvmstorebackend/eduvmstore/middleware/authentication_middleware.py
good find, is angepasst, müssen wir aber ja generell mal drüber gehen, dass die mal funktioniert

2024-12-01 19:37 UTC, samuelhilpert commented on eduvmstorebackend/eduvmstore/middleware/authentication_middleware.py
wurde im Pair Programming mit @val-cze gelöst

2024-12-01 19:37 UTC, samuelhilpert commented on eduvmstorebackend/eduvmstore/middleware/authentication_middleware.py
> +            create_user(user_dict)
nein, war ein fehler. 
wurde im Pair Programming mit @val-cze gelöst

2024-12-05 09:41 UTC, rickertmar approved these changes
Für mich sieht das alles gut aus. Good job!
Man könnte das ruff linting noch fixen, aber Hauptsache die Tests durchlaufen und alle Funktionalitäten laufen 👍🏼

2025-02-23 16:28 UTC, JaredHeinrich approved these changes

2025-02-23 16:28 UTC, merged